run_name: OLMo-2B-stella
seed: 3407
dry_run: false
# wandb:
#   name: ${run_name}
#   project: my-olmo-mixings-v3
#   entity: fulvwen
model:
  d_model: 2048
  n_heads: 16
  n_layers: 24
  mlp_ratio: 8
  weight_tying: false
  alibi: false
  rope: true
  flash_attention: true  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0
  pad_token_id: 0
  init_device: meta
  init_fn: mitchell
# compile: null  # causes instability on AMD GPUs
compile:
  backend: inductor
optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10
scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1
tokenizer:
  identifier:  /mnt/geogpt-gpfs/llm-course/home/zhangjianxing/hengxing_2B/configs/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right
save_folder: ${path.choose:${oc.env:SCRATCH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
save_overwrite: true
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: 15
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 10000
save_num_unsharded_checkpoints_to_keep: -1
load_path: /mnt/nfs15/sanqi/home/jiaminghui/output/run-1/step10000-unsharded/
sharded_checkpointer: torch_legacy
# 14 days time limit
time_limit: 1209600.0
max_duration: 739_328  # 3.1T tokens
global_train_batch_size: 2048
device_train_microbatch_size: 8
# device_train_microbatch_size: 16
precision: amp_bf16
fsdp:
  precision: mixed
  # wrapping_strategy: null
  # wrapping_strategy: size_based
  wrapping_strategy: by_block
  sharding_strategy: SHARD_GRAD_OP
max_grad_norm: 1.0
max_grad_norm_ratio: null
speed_monitor:
  window_size: 20
eval_interval: ${save_interval}
eval_subset_num_batches: -1
# device_eval_batch_size: 8
device_eval_batch_size: ${device_train_microbatch_size}
data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  paths:
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-117-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-055-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-171-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-069-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-009-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-011-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-012-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-036-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-127-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-125-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-008-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-089-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-03-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-119-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-047-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-073-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-13-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-145-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-122-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-090-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-111-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-057-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-080-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-095-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-076-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-043-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-148-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-020-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-035-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-121-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-066-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-029-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-096-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-103-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-006-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-081-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-085-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-033-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-030-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-093-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-062-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-126-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-153-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-170-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-160-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-109-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-023-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-105-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-116-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-053-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-124-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-144-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-123-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-112-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-034-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-082-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-176-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-157-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-08-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-107-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-143-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-178-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-141-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-131-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-000-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-018-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-015-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-159-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-104-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-142-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-061-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-049-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-151-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-166-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-11-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-100-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-099-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-040-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-087-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-158-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-169-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-060-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-09-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-139-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-133-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-130-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-00-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-10-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-037-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-083-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-005-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-092-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-032-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-024-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-129-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-046-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-039-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-108-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-045-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-110-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-003-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-147-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-098-00000.npy
  - /mnt/nfs15/sanqi/home/npy/fineweb_edu_sample_100BT/part-150-00000.npy
  - /mnt/nfs15/sanqi/home/npy/arxiv_astro/part-0-00000.npy
  - /mnt/nfs15/sanqi/home/npy/arxiv_astro/part-2-00000.npy
  - /mnt/nfs15/sanqi/home/npy/arxiv_astro/part-1-00000.npy
  - /mnt/nfs15/sanqi/home/npy/arxiv_astro/part-0-00000.npy
  - /mnt/nfs15/sanqi/home/npy/arxiv_astro/part-2-00000.npy
  - /mnt/nfs15/sanqi/home/npy/arxiv_astro/part-1-00000.npy
  - /mnt/nfs15/sanqi/home/npy/arxiv_astro/part-0-00000.npy
  - /mnt/nfs15/sanqi/home/npy/arxiv_astro/part-2-00000.npy
  - /mnt/nfs15/sanqi/home/npy/arxiv_astro/part-1-00000.npy
  - /mnt/nfs15/sanqi/home/npy/books/planet_book.npy
  - /mnt/nfs15/sanqi/home/npy/books/tianWen_book_1.npy
  - /mnt/nfs15/sanqi/home/npy/books/tianWen_book_0.npy
  - /mnt/nfs15/sanqi/home/npy/books/planet_book.npy
  - /mnt/nfs15/sanqi/home/npy/books/tianWen_book_1.npy
  - /mnt/nfs15/sanqi/home/npy/books/tianWen_book_0.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-05-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-02-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-03-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-08-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-09-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-00-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-06-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-04-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-01-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_astro/part-07-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-05-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-22-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-02-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-25-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-03-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-13-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-26-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-31-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-27-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-24-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-08-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-17-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-19-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-11-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-23-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-09-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-30-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-00-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-10-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-28-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-16-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-15-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-20-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-21-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-14-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-06-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-12-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-04-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-01-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-29-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-07-00000.npy
  - /mnt/nfs15/sanqi/home/npy/web_crawl_clean_v2/part-18-00000.npy
  - /mnt/nfs15/sanqi/home/npy/gits_astro/part-0-00000.npy
  - /mnt/nfs15/sanqi/home/npy/phd_thesis_v1_doc/part-0-00000.npy
  - /mnt/nfs15/sanqi/home/npy/phd_thesis_v1_paragraph/part-0-00000.npy
  - /mnt/nfs15/sanqi/home/npy/phd_thesis/part-0-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-08-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-17-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-19-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-11-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-23-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-09-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-00-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-10-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-16-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-15-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-20-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-21-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-14-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-06-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-12-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-04-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-01-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-07-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/StackExchange/part-18-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-05-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-22-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-02-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-25-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-03-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-13-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-26-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-31-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-27-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-24-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-08-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-17-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-19-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-11-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-23-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-09-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-30-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-00-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-10-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-28-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-27-00001.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-11-00001.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-16-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-15-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-20-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-21-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-14-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-06-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-12-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-04-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-01-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-29-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-07-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-20-00001.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-18-00000.npy
  - /mnt/nfs15/sanqi/home/npy/dolma_v1.7_subset/Arxiv/part-04-00001.npy
